version: "3.7"
services: 
  db:
    image: "postgres:latest"
    expose: 
      - 5400
    ports: 
      - "5400:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - netnetwork 
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "7171:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    networks: 
      - netnetwork
  redis:
    image: redis:latest
    networks:
      - netnetwork
    volumes:
      - /home/ubuntu/DockerConfig/redis.conf:/usr/redis/redis.conf
    command: redis-server /usr/redis/redis.conf
    container_name: redis    
  backend_pos:
    image: "backend"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/logfile:/backend/logfile
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 50M
    networks:
      - netnetwork 
    environment:
        PGUSER: rivaldi
        PGHOST: db
        PGDATABASE: mainDB
        PASSWORD: root
        PGPORT: 5432
        SERVICEPORT: 4500
        REDIS_PORT: 6379
        REDIS_PASSWORD: aldi1234
        REDIS_HOST: redis
  frontend_pos:
    container_name: "vue_frontend"
    image: "frontend"
    ports:
      - 80:80
    networks:
      - netnetwork
    depends_on:
      - backend_pos
    environment:
     -  VUE_APP_URL=http://3.92.255.131:8181/api
     -  VUE_APP_STATIC_URL=http://3.92.255.131:8181/api/public/upload/
    volumes: 
      - ./frontend:/dist/public
networks:
  netnetwork:
      
volumes:
  pgdata:
  pgadmin-data:
